from keyboard_controller import skill, move
import time


def run_berserker():

    skill('e')
    skill('h')
    time.sleep(1)
    skill('y')
    time.sleep(0.5)
    move('r', 2.5)
    skill('s')
    time.sleep(0.5)
    move('r', 1)
    skill('f')
    move('r', 3)
    time.sleep(0.3)
    move('r', 1.3)
    skill('w')
    time.sleep(0.3)
    move('r', 2.3)
    time.sleep(0.3)
    move('r', 1.2)
    skill('d')
    time.sleep(0.3)
    move('r', 2.6)
    time.sleep(0.3)
    move('r', 1)
    skill('t')
    time.sleep(0.3)
    move('r', 2.6)
    move('u', 0.3)
    time.sleep(0.3)
    move('r', 1.2)
    skill('g')
    time.sleep(0.8)
    skill('q')
    time.sleep(0.3)
    move('r', 3.5)
    time.sleep(0.4)
    skill('r')
